In [23]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [24]:
df = pd.read_csv(r".\datasets_globelEnv\Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# Label Encoder

In [ ]:
le = LabelEncoder()
df['LabelEncoder'] = le.fit_transform(df["Species"])    # 1D Array Expected

In [26]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,LabelEncoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0

# Ordinal Encoder

In [27]:
custom_order = [["Iris-setosa", "Iris-versicolor", "Iris-virginica"]]

oe = OrdinalEncoder(categories=custom_order)
df['OrdinalEncoder'] = oe.fit_transform(df[["Species"]])

In [28]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,LabelEncoder,OrdinalEncoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0,0.0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0,0.0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0,0.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0,0.0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0,0.0
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,2,2.0
146,147,6.3,2.5,5.0,1.9,Iris-virginica,2,2.0
147,148,6.5,3.0,5.2,2.0,Iris-virginica,2,2.0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,2,2.0
149,150,5.9,3.0,5.1,1.8,Iris-virginica,2,2.0

# OneHotEncoder

In [33]:
ohe = OneHotEncoder()
ohe_encoded = ohe.fit_transform(df[["Species"]])

In [34]:
print(ohe_encoded)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 150 stored elements and shape (150, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (125, 2)	1.0
  (126, 2)	1.0
  (127, 2)	1.0
  (128, 2)	1.0
  (129, 2)	1.0
  (130, 2)	1.0
  (131, 2)	1.0
  (132, 2)	1.0
  (133, 2)	1.0
  (134, 2)	1.0
  (135, 2)	1.0
  (136, 2)	1.0
  (137, 2)	1.0
  (138, 2)	1.0
  (139, 2)	1.0
  (140, 2)	1.0
  (141, 2)	1.0
  (142, 2)	1.0
  (143, 2)	1.0
  (144, 2)	1.0
  (145, 2)	1.0
  (146, 2)	1.0
  (147, 2)	1.0
  (148, 2)	1.0
  (149, 2)	1.0

In [35]:
type(ohe_encoded)

scipy.sparse._csr.csr_matrix

In [38]:
ohe_array = ohe_encoded.toarray()
ohe_array

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [39]:
feature_names = ohe.get_feature_names_out(['Species'])
feature_names

array(['Species_Iris-setosa', 'Species_Iris-versicolor',
       'Species_Iris-virginica'], dtype=object)

In [40]:
ohe_df = pd.DataFrame(ohe_array, columns=feature_names)
ohe_df

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                    1.0                      0.0                     0.0
1                    1.0                      0.0                     0.0
2                    1.0                      0.0                     0.0
3                    1.0                      0.0                     0.0
4                    1.0                      0.0                     0.0
..                   ...                      ...                     ...
145                  0.0                      0.0                     1.0
146                  0.0                      0.0                     1.0
147                  0.0                      0.0                     1.0
148                  0.0                      0.0                     1.0
149                  0.0                      0.0                     1.0

[150 rows x 3 columns]

In [41]:
final_df = pd.concat([df, ohe_df], axis=1)
final_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,LabelEncoder,OrdinalEncoder,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0,0.0,1.0,0.0,0.0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0,0.0,1.0,0.0,0.0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0,0.0,1.0,0.0,0.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0,0.0,1.0,0.0,0.0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,2,2.0,0.0,0.0,1.0
146,147,6.3,2.5,5.0,1.9,Iris-virginica,2,2.0,0.0,0.0,1.0
147,148,6.5,3.0,5.2,2.0,Iris-virginica,2,2.0,0.0,0.0,1.0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,2,2.0,0.0,0.0,1.0
149,150,5.9,3.0,5.1,1.8,Iris-virginica,2,2.0,0.0,0.0,1.0