# Feature Selection and Extraction

In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('../datasets_globelEnv/Iris.csv')

df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
X=df.drop(columns=['Id','Species']) #df.iloc[:,1:5] df.loc
y=df['Species']   #df.iloc[:,-1]

# Feature Selection

In [8]:
from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
df['Species']=lbl.fit_transform(df['Species'].values.reshape(-1,1))
y=df['Species']

d:\GitHub\CS-300-Introduction-to-Machine-Learning\globelEnv\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [9]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
X_new = SelectKBest(f_classif, k=3)
X_new=X_new.fit_transform(X,y)
X_new

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.4, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.5, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3, 0.3],
       [4.4, 1.3, 0.2],
       [5. , 1.6, 0.6],
       [5.1, 1.9, 0.4],
       [4.8, 1.4, 0.3],
       [5.1, 1.6, 0.2],
       [4.6, 1.4, 0.2],
       [5.3, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [7. , 4.7, 1.4],
       [6.4, 4.5, 1.5],
       [6.9, 4.9, 1.5],
       [5.5, 4. , 1.3],
       [6.5, 4.6, 1.5],
       [5.7, 4.5, 1.3],
       [6.3, 4.7, 1.6],
       [4.9, 3.3, 1. ],
       [6.6, 4.6, 1.3],
       [5.2, 3.9, 1.4],
       [5. , 3.5, 1. ],
       [5.9, 4.2, 1.5],
       [6. , 4. , 1. ],
       [6.1, 4.7, 1.4],
       [5.6, 3.6, 1.3],
       [6.7, 4.4, 1.4],
       [5.6, 4.5, 1.5],
       [5.8, 4.1, 1. ],
       [6.2, 4.5, 1.5],
       [5.6, 3.9, 1.1],
       [5.9, 4.8, 1.8],
       [6.1, 4. , 1.3],
       [6.3, 4.9, 1.5],
       [6.1, 4.7, 1.2],
       [6.4, 4.3, 1.3],
       [6.6, 4.4, 1.4],
       [6.8, 4.8, 1.4],
       [6.7, 5. , 1.7],
       [6. , 4.5, 1.5],
       [5.7, 3.5, 1. ],
       [5.5, 3.8, 1.1],
       [5.5, 3.7, 1. ],
       [5.8, 3.9, 1.2],
       [6. , 5.1, 1.6],
       [5.4, 4.5, 1.5],
       [6. , 4.5, 1.6],
       [6.7, 4.7, 1.5],
       [6.3, 4.4, 1.3],
       [5.6, 4.1, 1.3],
       [5.5, 4. , 1.3],
       [5.5, 4.4, 1.2],
       [6.1, 4.6, 1.4],
       [5.8, 4. , 1.2],
       [5. , 3.3, 1. ],
       [5.6, 4.2, 1.3],
       [5.7, 4.2, 1.2],
       [5.7, 4.2, 1.3],
       [6.2, 4.3, 1.3],
       [5.1, 3. , 1.1],
       [5.7, 4.1, 1.3],
       [6.3, 6. , 2.5],
       [5.8, 5.1, 1.9],
       [7.1, 5.9, 2.1],
       [6.3, 5.6, 1.8],
       [6.5, 5.8, 2.2],
       [7.6, 6.6, 2.1],
       [4.9, 4.5, 1.7],
       [7.3, 6.3, 1.8],
       [6.7, 5.8, 1.8],
       [7.2, 6.1, 2.5],
       [6.5, 5.1, 2. ],
       [6.4, 5.3, 1.9],
       [6.8, 5.5, 2.1],
       [5.7, 5. , 2. ],
       [5.8, 5.1, 2.4],
       [6.4, 5.3, 2.3],
       [6.5, 5.5, 1.8],
       [7.7, 6.7, 2.2],
       [7.7, 6.9, 2.3],
       [6. , 5. , 1.5],
       [6.9, 5.7, 2.3],
       [5.6, 4.9, 2. ],
       [7.7, 6.7, 2. ],
       [6.3, 4.9, 1.8],
       [6.7, 5.7, 2.1],
       [7.2, 6. , 1.8],
       [6.2, 4.8, 1.8],
       [6.1, 4.9, 1.8],
       [6.4, 5.6, 2.1],
       [7.2, 5.8, 1.6],
       [7.4, 6.1, 1.9],
       [7.9, 6.4, 2. ],
       [6.4, 5.6, 2.2],
       [6.3, 5.1, 1.5],
       [6.1, 5.6, 1.4],
       [7.7, 6.1, 2.3],
       [6.3, 5.6, 2.4],
       [6.4, 5.5, 1.8],
       [6. , 4.8, 1.8],
       [6.9, 5.4, 2.1],
       [6.7, 5.6, 2.4],
       [6.9, 5.1, 2.3],
       [5.8, 5.1, 1.9],
       [6.8, 5.9, 2.3],
       [6.7, 5.7, 2.5],
       [6.7, 5.2, 2.3],
       [6.3, 5. , 1.9],
       [6.5, 5.2, 2. ],
       [6.2, 5.4, 2.3],
       [5.9, 5.1, 1.8]])

In [10]:
from sklearn.datasets import load_diabetes

dia_X, dia_y = load_diabetes(as_frame=True, return_X_y=True)
dia_X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [ ]:
# dia_X_new = SelectKBest(f_classif, k=5)
# dia_X_new=dia_X_new.fit_transform(dia_X,dia_y)
# dia_X_new

In [18]:
dia_X_new = SelectKBest(f_classif, k=5).set_output(transform='pandas')
dia_X_new=dia_X_new.fit_transform(dia_X,dia_y)
dia_X_new.columns

Index(['bmi', 'bp', 's3', 's4', 's5'], dtype='str')

In [19]:
dia_X_new

          bmi        bp        s3        s4        s5
0    0.061696  0.021872 -0.043401 -0.002592  0.019907
1   -0.051474 -0.026328  0.074412 -0.039493 -0.068332
2    0.044451 -0.005670 -0.032356 -0.002592  0.002861
3   -0.011595 -0.036656 -0.036038  0.034309  0.022688
4   -0.036385  0.021872  0.008142 -0.002592 -0.031988
..        ...       ...       ...       ...       ...
437  0.019662  0.059744 -0.028674 -0.002592  0.031193
438 -0.015906 -0.067642 -0.028674  0.034309 -0.018114
439 -0.015906  0.017293 -0.024993 -0.011080 -0.046883
440  0.039062  0.001215 -0.028674  0.026560  0.044529
441 -0.073030 -0.081413  0.173816 -0.039493 -0.004222

[442 rows x 5 columns]

# Feature Extraction

In [28]:
from sklearn.decomposition import PCA

# PCA 2
pca = PCA(n_components=2)
X_pca = pca.fit_transform(dia_X)
X_pca

array([[ 2.79302143e-02, -9.26013646e-02],
       [-1.34686684e-01,  6.52632727e-02],
       [ 1.29438351e-02, -7.77643220e-02],
       [ 2.34406501e-03,  1.81831115e-02],
       [-3.59792948e-02,  3.86210104e-02],
       [-1.88658648e-01, -1.81251811e-02],
       [-9.48362169e-02, -3.83153020e-02],
       [ 9.87389141e-02,  8.69445676e-02],
       [ 2.86822631e-02, -4.19165932e-02],
       [-1.00905803e-02, -2.34443516e-02],
       [-1.83420944e-01, -7.28738636e-02],
       [ 1.88791436e-02, -3.00866109e-02],
       [-7.59310434e-02,  4.66834546e-02],
       [ 1.51476346e-02, -3.09692531e-02],
       [-8.01680343e-02,  8.64702045e-02],
       [ 1.40489680e-01,  4.51900438e-02],
       [ 7.58472275e-03,  4.33938287e-02],
       [ 1.08837693e-01, -7.06847922e-03],
       [-5.49928895e-02, -2.03721799e-02],
       [-8.42647445e-02,  4.41809113e-02],
       [-9.55938999e-02, -1.37939377e-02],
       [-9.18736436e-02, -3.95422482e-02],
       [-7.97264785e-02,  3.42316636e-02],
       [ 1.79488925e-01, -8.39239510e-02],
       [-6.13395932e-02, -1.18647819e-02],
       [ 3.92289797e-03, -5.10815831e-02],
       [-1.84827979e-01, -4.67873276e-02],
       [-4.96968646e-02, -2.63118063e-02],
       [-8.36794754e-02, -2.87315084e-03],
       [-1.71888452e-02, -6.69918566e-02],
       [-5.58612706e-02,  1.70261900e-02],
       [-1.64968454e-01,  3.10721686e-02],
       [ 1.24056413e-01, -1.39902254e-01],
       [-1.36512070e-01,  2.59189070e-02],
       [-1.40161670e-01, -5.63355535e-03],
       [-3.34424701e-02,  8.95452998e-02],
       [-6.77614763e-03,  2.10248325e-02],
       [-6.69445835e-02,  7.15279250e-03],
       [ 1.85193066e-01,  2.08698212e-02],
       [ 7.28675450e-03, -1.49529076e-02],
       [ 1.15507114e-01,  2.04193015e-02],
       [-1.74464005e-01, -2.47391588e-02],
       [-2.76535738e-02, -8.51264414e-02],
       [-8.56907362e-02,  9.88694527e-02],
       [ 9.67997109e-02, -7.97604211e-02],
       [-1.01486317e-02, -2.33658967e-02],
       [-1.15569604e-01, -1.48484343e-02],
       [-1.61763082e-01, -5.13032231e-02],
       [-4.07020176e-02,  1.94687577e-02],
       [ 6.12596235e-02, -6.87902545e-02],
       [-4.92361498e-02, -2.33380393e-02],
       [ 9.78358813e-03, -7.29738140e-02],
       [-1.46170649e-02,  7.55584532e-02],
       [ 1.34675753e-02,  3.15081933e-02],
       [-4.08832622e-02,  5.95151542e-02],
       [-1.16621627e-01,  6.08978954e-02],
       [-1.52021504e-02, -3.73506274e-02],
       [-2.05136652e-01, -2.71312302e-02],
       [-1.25906203e-01,  1.06046270e-01],
       [ 6.89943948e-02,  5.74905369e-02],
       [-1.64254405e-01, -1.75853723e-02],
       [ 3.57728639e-02, -1.00595142e-01],
       [-9.15918013e-02,  1.04198797e-02],
       [-5.32321057e-02,  6.15060303e-02],
       [-5.72412644e-02, -6.99817153e-02],
       [ 8.24591868e-02, -5.10086971e-02],
       [ 4.76620720e-02, -6.23897662e-02],
       [ 9.97591072e-03, -1.93737816e-02],
       [-2.42696192e-02, -4.26790608e-02],
       [-9.41294250e-02, -5.02133203e-02],
       [-8.43450896e-02,  6.22569623e-02],
       [ 8.47077299e-02,  9.74560100e-03],
       [ 8.04791546e-02,  9.46796756e-02],
       [ 4.89558218e-02,  2.59064029e-02],
       [ 4.01472366e-02,  1.35415653e-02],
       [ 2.99986064e-03, -3.15321715e-02],
       [-6.25671658e-02, -1.81237706e-01],
       [-1.33201177e-01,  6.76728629e-03],
       [-7.47465917e-02, -6.15645677e-02],
       [-8.00470134e-02,  4.28855110e-02],
       [ 5.75578499e-02,  1.04340565e-01],
       [ 2.91401208e-02, -5.13136427e-03],
       [-1.09965914e-01,  1.14348007e-01],
       [-9.91678462e-02, -3.61462954e-02],
       [-1.69801743e-01,  4.60491667e-02],
       [-4.02222544e-02,  1.95493805e-02],
       [-9.98401410e-02, -5.61050825e-02],
       [-1.02180256e-02,  1.15876937e-01],
       [-7.48947450e-02, -2.45996601e-02],
       [-8.27388257e-02,  5.36623524e-02],
       [-1.29084819e-01,  3.49861839e-02],
       [ 8.50736043e-02,  7.40964738e-02],
       [-1.66685012e-02,  2.92259859e-02],
       [-1.41107773e-01,  7.13806086e-02],
       [-1.20859993e-01,  5.93103749e-02],
       [-7.92917190e-02, -2.62520733e-02],
       [ 9.26094502e-02, -6.21822663e-02],
       [ 7.81674911e-02,  1.21811753e-02],
       [-4.84811358e-02, -1.93736646e-02],
       [ 2.85587055e-03,  5.33632352e-02],
       [ 3.47062070e-02,  8.78325309e-02],
       [-1.47061785e-02,  1.79569412e-02],
       [-3.77500658e-02,  7.47773262e-02],
       [ 8.81231657e-02,  1.30685982e-02],
       [-7.67499699e-02,  5.26285486e-03],
       [-1.95769292e-02, -4.43799355e-02],
       [-1.60841513e-01,  4.41607413e-03],
       [ 2.82976385e-02,  3.93078077e-03],
       [ 5.71462252e-02, -1.34327891e-01],
       [ 9.05189385e-02, -3.83286338e-02],
       [-9.68604247e-02, -3.63782196e-02],
       [-5.80803414e-02,  8.02586338e-02],
       [-2.72176649e-02,  2.49412339e-02],
       [ 1.22241667e-01, -4.69044642e-02],
       [ 1.01544068e-01, -3.35822699e-02],
       [ 1.33537730e-01,  5.42871517e-03],
       [ 1.06804623e-01, -3.51487531e-02],
       [ 1.65985466e-01,  9.19062686e-03],
       [ 7.50809866e-02, -2.02279784e-02],
       [-4.86811180e-02,  1.16925688e-02],
       [-5.20168305e-02, -2.29385753e-02],
       [ 6.30818723e-02,  6.68918406e-03],
       [ 1.62078822e-01, -1.61519406e-02],
       [ 2.69644678e-01,  1.02843254e-01],
       [-5.94325872e-02, -9.57375590e-03],
       [ 1.32525415e-02, -8.70550111e-02],
       [-1.89155374e-01,  3.21542322e-03],
       [-3.73832120e-02,  6.24825051e-02],
       [-1.09677617e-01,  4.75842709e-02],
       [ 8.27347915e-02, -3.30857829e-03],
       [ 8.35866370e-02, -6.57444590e-02],
       [-1.43950754e-01,  3.57582484e-02],
       [ 3.40856027e-02,  2.60274437e-02],
       [-1.33981221e-01, -8.27847478e-02],
       [-7.62123221e-02,  5.83073344e-02],
       [ 4.02905005e-02, -7.96518478e-02],
       [-1.92208547e-01,  1.43953561e-03],
       [ 2.62886457e-02, -2.24825743e-02],
       [ 8.79167871e-02, -9.73736656e-02],
       [ 2.67560762e-02, -5.61017936e-02],
       [ 2.70168427e-02, -6.61461792e-02],
       [ 1.57247998e-01, -1.04831906e-03],
       [ 8.17956801e-02,  2.79685248e-02],
       [-7.40935303e-02,  7.53525512e-02],
       [ 1.02398817e-01, -2.35328736e-02],
       [-2.68459147e-02, -3.39212939e-02],
       [ 7.13549754e-02, -3.43687931e-02],
       [ 5.75998414e-02,  1.79829995e-03],
       [ 6.97273017e-03,  3.19610277e-02],
       [ 3.10930000e-02, -7.39351968e-02],
       [ 5.72444796e-03, -3.75117909e-02],
       [-6.14826514e-02,  3.35917517e-02],
       [ 1.56622765e-01, -2.48707978e-02],
       [ 1.99933089e-02, -2.16346550e-02],
       [ 4.89716148e-02,  2.83350966e-03],
       [ 1.40491307e-01,  4.21148356e-02],
       [-7.95573704e-02, -7.55491027e-03],
       [ 4.52611060e-02,  1.45365226e-02],
       [-7.38321932e-02,  4.90829555e-02],
       [ 4.76711433e-02,  2.70022758e-03],
       [-1.08978800e-01,  2.71954961e-02],
       [ 2.43969921e-01,  5.82736390e-02],
       [-5.51486332e-02,  1.38538964e-03],
       [ 6.64101499e-02, -5.08580700e-02],
       [-3.66278573e-02,  8.28170912e-02],
       [-1.34679633e-01,  2.11024117e-02],
       [-1.62413538e-01, -8.39322771e-02],
       [ 1.36986923e-01, -1.44816997e-02],
       [ 2.00643706e-01, -1.37468684e-02],
       [ 1.11929004e-01,  7.13749283e-03],
       [-8.76088258e-02,  1.17378020e-02],
       [-1.47012785e-01, -3.44922133e-02],
       [ 1.36267449e-01, -2.12817172e-02],
       [-1.16535885e-01, -7.79770614e-02],
       [-5.91836519e-02, -1.31326774e-01],
       [-6.13805474e-02,  6.89633273e-03],
       [ 5.36770304e-02,  2.00408651e-04],
       [ 1.07563240e-01, -1.01446003e-03],
       [-5.97767157e-02,  8.78516236e-02],
       [ 2.91189791e-02,  2.70788362e-02],
       [ 4.43428459e-02, -5.71713868e-02],
       [-3.31303375e-02,  1.05693521e-01],
       [ 1.34447327e-01,  2.67895108e-02],
       [ 4.97179077e-02, -3.42778042e-02],
       [ 1.09456402e-02, -2.86868011e-02],
       [ 2.76775263e-02, -7.94077704e-02],
       [ 1.04602000e-01, -1.85097075e-02],
       [-2.14660308e-01, -1.34557336e-02],
       [ 3.82714219e-02,  1.09603874e-01],
       [-4.90221386e-02,  3.60160246e-02],
       [ 2.47645058e-02, -2.33553833e-02],
       [-7.74122437e-02, -1.01009828e-01],
       [-2.82553138e-02,  3.28895285e-02],
       [ 1.09008223e-01,  4.11590332e-02],
       [-7.26373172e-02, -3.74040413e-02],
       [ 8.95477371e-02, -1.20703842e-02],
       [-3.30996011e-02,  8.24621753e-02],
       [ 8.87875709e-02, -5.97077725e-02],
       [-1.01457879e-01, -3.44134681e-02],
       [ 2.54944237e-02,  5.63700527e-02],
       [-2.13997137e-03,  1.08921909e-01],
       [-6.40282049e-02,  1.31913283e-03],
       [ 1.44264886e-01,  1.00559400e-01],
       [ 1.26577079e-01, -1.11690130e-02],
       [ 8.50044613e-02, -7.17175131e-02],
       [-4.78623185e-03, -2.33771883e-02],
       [ 6.25563069e-02, -4.35561220e-03],
       [ 1.92322458e-02,  1.90899993e-02],
       [ 1.11386516e-01,  2.16810505e-03],
       [ 3.44176908e-02, -1.00795295e-01],
       [-3.10844041e-02,  1.10699840e-01],
       [-1.83106545e-02, -3.79961703e-03],
       [ 1.40434369e-02,  9.41311894e-02],
       [-6.72016766e-02,  4.63299212e-02],
       [-1.57494868e-01,  2.65399818e-02],
       [ 1.06626257e-01, -1.12800844e-01],
       [ 1.95605139e-01, -1.72411684e-02],
       [ 9.53281341e-02,  4.85412625e-02],
       [-1.97790212e-02,  1.11063912e-02],
       [-1.22931941e-01, -3.99624693e-02],
       [-1.07735781e-01, -3.73775984e-02],
       [-4.58754083e-02,  3.54390680e-03],
       [-3.12679681e-02, -8.49035090e-02],
       [-1.39110872e-01, -2.18378428e-02],
       [-1.30347747e-01, -5.61512860e-04],
       [ 6.94488682e-02, -1.12267059e-01],
       [-1.09607468e-01, -1.52486182e-02],
       [-2.99930488e-02,  1.43574507e-02],
       [-6.84192378e-02,  4.00577314e-02],
       [-4.21293481e-02,  1.09852602e-02],
       [ 1.86969353e-01,  1.23034964e-01],
       [ 8.39411888e-04,  2.92896071e-02],
       [ 9.76655540e-02,  4.07980283e-03],
       [-6.94258408e-02,  2.34456969e-02],
       [ 5.45985617e-02, -1.92471477e-03],
       [ 3.96309988e-02, -1.08311701e-01],
       [ 9.08578758e-02,  9.38229749e-02],
       [-8.36153667e-02,  6.61180745e-02],
       [ 6.45937000e-02, -9.09504410e-02],
       [ 6.33499633e-02,  1.09020813e-01],
       [ 1.02678471e-01, -7.18099654e-02],
       [ 3.10503942e-02,  4.15293869e-03],
       [-1.44492173e-01, -9.61210635e-02],
       [-4.34352374e-02, -3.98633482e-02],
       [-6.83866423e-02, -6.29585477e-02],
       [-1.59181917e-01, -3.18352969e-03],
       [-2.65694858e-03,  1.34409966e-01],
       [-1.38092194e-01,  7.15636739e-02],
       [ 1.92799196e-01,  1.06147512e-01],
       [ 9.70240322e-02,  2.70710971e-02],
       [ 7.30139836e-02, -4.58617267e-02],
       [ 1.97243312e-01, -3.49780772e-02],
       [ 4.54430424e-02,  3.13629150e-02],
       [ 1.14773989e-01,  5.20953169e-02],
       [ 1.81925772e-01, -4.88781597e-02],
       [-6.61641731e-02,  3.84818161e-02],
       [ 4.23514434e-02, -5.71279455e-02],
       [-6.72032580e-02,  3.25551282e-03],
       [ 8.67666991e-02, -2.28876418e-02],
       [-9.86182115e-03,  2.12912970e-03],
       [-1.37378849e-01,  1.04270681e-01],
       [-6.16465672e-02,  1.14248961e-01],
       [ 1.17755167e-01, -5.07147226e-02],
       [-1.21667464e-01, -3.77699300e-02],
       [-1.89207085e-02, -7.05876454e-02],
       [-1.37433094e-03, -1.40243718e-02],
       [-1.32669276e-01,  3.37497520e-02],
       [ 6.64772063e-02,  1.08200214e-01],
       [ 1.68993761e-01, -4.90559513e-02],
       [-1.06910827e-01,  1.35216493e-01],
       [ 1.21302626e-04, -6.96877016e-02],
       [ 1.54248801e-02, -7.93849753e-02],
       [-1.14949082e-01, -4.91539585e-02],
       [ 1.61572718e-01,  8.98472021e-03],
       [ 7.58858526e-03,  2.76712380e-03],
       [ 2.62757632e-02, -5.61591817e-02],
       [ 9.04278227e-02,  1.51040901e-01],
       [-1.34142430e-01, -3.26694017e-03],
       [ 3.52628095e-02, -2.69337269e-02],
       [-4.24983250e-02, -2.86603424e-02],
       [ 3.14383678e-02, -1.57111299e-03],
       [-6.19630095e-02, -3.38971154e-02],
       [ 8.72464306e-02,  1.20787045e-01],
       [-1.22754150e-01,  4.15159909e-03],
       [-1.93575547e-02, -1.03286530e-01],
       [ 7.91994713e-02, -5.97812577e-03],
       [-1.77667178e-01,  5.37962619e-02],
       [ 1.02094755e-01,  1.58139993e-01],
       [ 1.64480589e-02,  5.65181890e-02],
       [ 9.12123013e-02,  3.37593960e-03],
       [ 1.14682055e-01, -5.85390864e-02],
       [ 6.63539391e-02,  7.16152488e-02],
       [-1.51738239e-01,  1.50674991e-02],
       [ 8.85314916e-03,  3.08260452e-02],
       [-2.68902474e-02, -2.57355994e-02],
       [-2.06015439e-02, -2.36457179e-02],
       [-1.07719820e-01,  3.54328091e-02],
       [-1.10237347e-01,  5.47551434e-03],
       [-9.11575448e-02, -1.04515481e-01],
       [-1.82263287e-02, -5.02856943e-02],
       [ 3.40623109e-02, -8.34545469e-03],
       [ 2.98440052e-02,  1.91547568e-02],
       [ 5.89654753e-02,  3.23134934e-02],
       [ 8.41436653e-02,  5.60346253e-02],
       [ 1.17411365e-01,  5.48774529e-02],
       [ 2.14576597e-02, -3.84579374e-02],
       [-3.97204733e-02, -5.38641508e-02],
       [ 9.48530462e-02, -6.49436965e-03],
       [-1.76049128e-01, -1.40513446e-02],
       [ 8.50519387e-02,  6.73765493e-02],
       [ 3.22813422e-02, -1.49748672e-03],
       [ 7.98771773e-02,  6.11530167e-02],
       [-9.08244267e-02,  1.41117311e-02],
       [ 1.09242013e-01, -1.36477668e-02],
       [-2.55925446e-02,  7.85960067e-03],
       [-4.63445944e-02,  8.71043162e-02],
       [ 7.57808130e-02, -5.44347233e-02],
       [ 9.73876582e-02,  7.60860467e-02],
       [ 1.22752389e-02,  6.96563157e-02],
       [-1.98700509e-02,  4.67128371e-03],
       [ 1.03875355e-01,  8.64725618e-02],
       [ 2.20712306e-01, -5.60728353e-03],
       [ 2.15121619e-01, -1.06363752e-01],
       [ 1.84087736e-01, -3.27367760e-02],
       [ 1.47394102e-01,  6.37593956e-02],
       [ 1.30785708e-01,  5.12969672e-02],
       [ 5.19790585e-02, -4.07913435e-02],
       [ 5.90699819e-02,  3.45104878e-02],
       [-2.34007501e-02, -2.04333996e-02],
       [-4.50693160e-02, -3.12435069e-02],
       [ 8.92530808e-02, -5.34012684e-02],
       [-3.82209931e-02, -8.67867747e-02],
       [ 1.07591204e-01, -5.63197262e-02],
       [ 6.75358312e-02, -6.69608870e-02],
       [-1.25542853e-01, -7.34541858e-02],
       [-1.00473584e-01,  6.55568780e-02],
       [ 1.93608353e-01,  5.38302571e-02],
       [ 5.66103381e-02, -5.24251644e-02],
       [-5.39343226e-02,  2.89815639e-02],
       [ 3.82061988e-02,  1.10533543e-01],
       [-3.05068912e-02,  8.94711871e-03],
       [ 3.52431076e-02, -6.15503632e-02],
       [ 5.42354797e-02, -4.16924657e-02],
       [-2.50998613e-02,  2.97686370e-02],
       [ 5.27203635e-03,  7.04838164e-02],
       [ 6.91954084e-02,  3.23786170e-02],
       [ 1.78619520e-01,  8.61606685e-02],
       [-3.10074433e-02, -1.09742068e-02],
       [-6.46780933e-02,  4.92453270e-02],
       [-7.28477909e-02, -1.25776323e-01],
       [ 1.19248780e-01, -6.08897053e-02],
       [-1.33445744e-01, -8.62991771e-02],
       [-1.60384038e-01, -5.82651055e-03],
       [ 4.63969763e-02,  7.64420230e-02],
       [ 1.55339465e-01,  6.36323799e-02],
       [-3.19909835e-02, -6.17501725e-02],
       [-3.82232472e-02,  1.47677673e-02],
       [ 3.95458082e-03, -6.09299443e-02],
       [-1.49984298e-01,  2.76101376e-02],
       [ 8.36770746e-02, -3.20029651e-02],
       [ 1.67574886e-02, -9.23915082e-03],
       [-9.25996522e-02,  1.26539157e-03],
       [ 6.32167341e-02, -9.35493214e-02],
       [ 6.97256925e-03, -9.42998923e-02],
       [ 6.42825282e-02, -5.04158781e-02],
       [ 3.33429100e-02,  2.20246784e-02],
       [ 1.47534180e-01, -3.55669925e-02],
       [ 1.29279583e-01, -3.28276760e-02],
       [ 9.51697957e-02, -3.90373697e-02],
       [ 6.48736189e-03, -2.48750644e-02],
       [-1.27627255e-01,  7.68709417e-02],
       [ 1.00244842e-01, -1.33147813e-02],
       [-1.84977463e-02,  1.44289946e-02],
       [-1.04600480e-01, -4.51635583e-02],
       [-1.52086861e-01, -2.77242577e-02],
       [ 7.61692167e-02,  9.81832463e-03],
       [ 1.58571055e-01,  1.15476115e-01],
       [ 7.38783046e-02, -2.48827942e-02],
       [ 3.93528967e-02, -4.21304777e-02],
       [-1.41862287e-01, -7.89464070e-02],
       [-5.58208124e-02, -5.03674430e-02],
       [-9.14835923e-02, -4.59791209e-02],
       [ 4.29690648e-02, -6.11438501e-02],
       [-4.54388917e-02, -3.83161349e-02],
       [ 5.78458017e-02,  9.91117083e-02],
       [-5.34756434e-02, -7.98585587e-02],
       [-7.21817308e-02,  4.35717665e-02],
       [-1.13833468e-01, -1.84126567e-02],
       [ 2.71766663e-02, -3.56256655e-02],
       [-9.87127053e-02,  1.35503919e-02],
       [ 1.37345877e-01, -7.38472595e-02],
       [-1.62676698e-01, -1.98535178e-03],
       [ 1.20693175e-02,  1.44210940e-02],
       [-1.11848229e-01,  1.33456311e-02],
       [ 1.06677833e-01, -5.36816609e-02],
       [-4.91711402e-02,  1.45636079e-02],
       [-1.35395857e-01, -5.86427484e-02],
       [-2.90564764e-02, -3.72694007e-02],
       [ 1.05213158e-02,  6.14803253e-02],
       [ 7.66937385e-02, -2.21833749e-02],
       [-4.66919725e-02,  1.02213735e-02],
       [-1.21785888e-01,  2.90953088e-02],
       [ 9.10499670e-02, -3.98878843e-02],
       [ 4.61701377e-02, -2.78473834e-02],
       [-3.01936454e-02, -2.50720383e-02],
       [ 3.13352185e-02, -1.87534976e-01],
       [-1.86035733e-01,  3.38402249e-02],
       [ 3.32554031e-02,  1.76005308e-02],
       [ 8.71334690e-02,  2.43916069e-02],
       [ 1.06440610e-01,  1.22333861e-02],
       [ 6.49625073e-02,  1.26958457e-02],
       [-1.17858604e-01, -4.20590676e-02],
       [ 8.50908547e-02,  1.35699525e-02],
       [-5.88466608e-02,  5.47234927e-02],
       [ 1.78440789e-01,  7.52563922e-02],
       [ 5.43678829e-02,  3.15223069e-02],
       [ 4.90779181e-02, -1.50018724e-02],
       [-5.12968049e-02,  9.36558653e-03],
       [ 1.92307203e-02,  1.60667234e-01],
       [-1.36840862e-01, -2.06858435e-02],
       [ 3.24094859e-02,  1.18480202e-02],
       [ 1.24745772e-01, -9.65144978e-03],
       [ 8.38311468e-02,  4.50281454e-02],
       [ 1.04066677e-01, -2.18217037e-03],
       [ 4.56184401e-02, -5.86867895e-02],
       [-1.97220711e-01, -5.60600868e-02],
       [ 1.36545716e-01,  1.69460638e-02],
       [-6.69382061e-02, -9.38800174e-02],
       [ 1.79598406e-01, -4.10155270e-02],
       [-5.16536687e-02,  1.03378704e-01],
       [-4.45144807e-03,  5.07923514e-02],
       [-4.05545410e-02, -3.71297971e-02],
       [ 1.10531974e-01,  4.96334922e-02],
       [-9.14927570e-02,  1.32092811e-01],
       [-2.89019546e-02,  4.11250155e-02],
       [-5.62727929e-02,  1.39575517e-02],
       [-1.78998931e-01,  5.53235422e-02],
       [ 5.89581860e-02, -4.92759532e-02],
       [ 6.01565579e-02,  3.62122367e-02],
       [-9.76067230e-03, -5.73391803e-02],
       [ 3.29565183e-02,  9.99472701e-03],
       [-9.05612226e-02,  1.89108406e-01]])