# StandardScaler, MinMaxScaler, and MaxAbsScaler

In [14]:
import pandas as pd

iris = pd.read_csv('../datasets_globelEnv/Iris.csv')

iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Standard Scaler

In [16]:
from sklearn.preprocessing import StandardScaler
sscaler = StandardScaler()

iris['Std_Scaled_SepalLengthCM'] = sscaler.fit_transform(iris[['SepalLengthCm']])
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Std_Scaled_SepalLengthCM
0,1,5.1,3.5,1.4,0.2,Iris-setosa,-0.900681
1,2,4.9,3.0,1.4,0.2,Iris-setosa,-1.143017
2,3,4.7,3.2,1.3,0.2,Iris-setosa,-1.385353
3,4,4.6,3.1,1.5,0.2,Iris-setosa,-1.506521
4,5,5.0,3.6,1.4,0.2,Iris-setosa,-1.021849
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,1.038005
146,147,6.3,2.5,5.0,1.9,Iris-virginica,0.553333
147,148,6.5,3.0,5.2,2.0,Iris-virginica,0.795669
148,149,6.2,3.4,5.4,2.3,Iris-virginica,0.432165
149,150,5.9,3.0,5.1,1.8,Iris-virginica,0.068662

In [17]:
print(sscaler.mean_)
print(sscaler.var_)
print(sscaler.scale_)

[5.84333333]
[0.68112222]
[0.82530129]

In [ ]:
# Inverse Transform
iris['Std_Invert_SepalLengthCM'] = sscaler.inverse_transform(iris[['Std_Scaled_SepalLengthCM']])

iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Std_Scaled_SepalLengthCM,Std_Invert_SepalLengthCM
0,1,5.1,3.5,1.4,0.2,Iris-setosa,-0.900681,5.1
1,2,4.9,3.0,1.4,0.2,Iris-setosa,-1.143017,4.9
2,3,4.7,3.2,1.3,0.2,Iris-setosa,-1.385353,4.7
3,4,4.6,3.1,1.5,0.2,Iris-setosa,-1.506521,4.6
4,5,5.0,3.6,1.4,0.2,Iris-setosa,-1.021849,5.0
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,1.038005,6.7
146,147,6.3,2.5,5.0,1.9,Iris-virginica,0.553333,6.3
147,148,6.5,3.0,5.2,2.0,Iris-virginica,0.795669,6.5
148,149,6.2,3.4,5.4,2.3,Iris-virginica,0.432165,6.2
149,150,5.9,3.0,5.1,1.8,Iris-virginica,0.068662,5.9