# StandardScaler, MinMaxScaler, and MaxAbsScaler

In [10]:
import pandas as pd

iris = pd.read_csv('../datasets_globelEnv/Iris.csv')

iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Standard Scaler

In [11]:
from sklearn.preprocessing import StandardScaler
sscaler = StandardScaler()

iris['Std_Scaled_SepalLengthCM'] = sscaler.fit_transform(iris[['SepalLengthCm']])

# Inverse Transform
iris['Std_Inverse_SepalLengthCM'] = sscaler.inverse_transform(iris[['Std_Scaled_SepalLengthCM']])

iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Std_Scaled_SepalLengthCM,Std_Inverse_SepalLengthCM
0,1,5.1,3.5,1.4,0.2,Iris-setosa,-0.900681,5.1
1,2,4.9,3.0,1.4,0.2,Iris-setosa,-1.143017,4.9
2,3,4.7,3.2,1.3,0.2,Iris-setosa,-1.385353,4.7
3,4,4.6,3.1,1.5,0.2,Iris-setosa,-1.506521,4.6
4,5,5.0,3.6,1.4,0.2,Iris-setosa,-1.021849,5.0
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,1.038005,6.7
146,147,6.3,2.5,5.0,1.9,Iris-virginica,0.553333,6.3
147,148,6.5,3.0,5.2,2.0,Iris-virginica,0.795669,6.5
148,149,6.2,3.4,5.4,2.3,Iris-virginica,0.432165,6.2
149,150,5.9,3.0,5.1,1.8,Iris-virginica,0.068662,5.9

In [ ]:
print(sscaler.mean_)    # Original Mean
print(sscaler.var_)     # Original Var
print(sscaler.scale_)   # Original Std

[5.84333333]
[0.68112222]
[0.82530129]

In [ ]:
print(iris['Std_Scaled_SepalLengthCM'].mean())      # approx. zero
print(iris['Std_Scaled_SepalLengthCM'].std(ddof=0)) # 1

-4.736951571734001e-16
1.0

# MinMaxScaler

In [13]:
from sklearn.preprocessing import MinMaxScaler

mmscaler = MinMaxScaler(feature_range=(0,1))

iris['MM_Scaled_SepalLengthCM'] = mmscaler.fit_transform(iris[['SepalLengthCm']])
iris['MM_Inverse_SepallengthCM'] = mmscaler.inverse_transform(iris[['MM_Scaled_SepalLengthCM']])
iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Std_Scaled_SepalLengthCM,Std_Inverse_SepalLengthCM,MM_Scaled_SepalLengthCM,MM_Inverse_SepallengthCM
0,1,5.1,3.5,1.4,0.2,Iris-setosa,-0.900681,5.1,0.222222,5.1
1,2,4.9,3.0,1.4,0.2,Iris-setosa,-1.143017,4.9,0.166667,4.9
2,3,4.7,3.2,1.3,0.2,Iris-setosa,-1.385353,4.7,0.111111,4.7
3,4,4.6,3.1,1.5,0.2,Iris-setosa,-1.506521,4.6,0.083333,4.6
4,5,5.0,3.6,1.4,0.2,Iris-setosa,-1.021849,5.0,0.194444,5.0

In [14]:
print(mmscaler.data_max_)
print(mmscaler.data_min_)
print(mmscaler.data_range_)

[7.9]
[4.3]
[3.6]

In [19]:
print(iris['MM_Scaled_SepalLengthCM'].min())
print(iris['MM_Scaled_SepalLengthCM'].max())

0.0
1.0

# MaxAbsScaler

In [15]:
from sklearn.preprocessing import MaxAbsScaler

mascaler = MaxAbsScaler()

iris['MA_Scaled_SepalLengthCM'] = mascaler.fit_transform(iris[['SepalLengthCm']])
iris['MA_Inverse_SepallengthCM'] = mascaler.inverse_transform(iris[['MA_Scaled_SepalLengthCM']])
iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Std_Scaled_SepalLengthCM,Std_Inverse_SepalLengthCM,MM_Scaled_SepalLengthCM,MM_Inverse_SepallengthCM,MA_Scaled_SepalLengthCM,MA_Inverse_SepallengthCM
0,1,5.1,3.5,1.4,0.2,Iris-setosa,-0.900681,5.1,0.222222,5.1,0.645570,5.1
1,2,4.9,3.0,1.4,0.2,Iris-setosa,-1.143017,4.9,0.166667,4.9,0.620253,4.9
2,3,4.7,3.2,1.3,0.2,Iris-setosa,-1.385353,4.7,0.111111,4.7,0.594937,4.7
3,4,4.6,3.1,1.5,0.2,Iris-setosa,-1.506521,4.6,0.083333,4.6,0.582278,4.6
4,5,5.0,3.6,1.4,0.2,Iris-setosa,-1.021849,5.0,0.194444,5.0,0.632911,5.0

In [ ]:
print(mascaler.max_abs_)    # largest absolute value found - Speal Lenght
print(mascaler.scale_)      # actual scaling factor used to transform the feature

[7.9]
[7.9]

In [20]:
print(iris['MA_Scaled_SepalLengthCM'].min())
print(iris['MA_Scaled_SepalLengthCM'].max())

0.5443037974683543
1.0