In [2]:
import pandas as pd 
df=pd.read_csv('data/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [5]:
transformed_data=scaler.fit_transform(df[['SepalLengthCm']])
transformed_data.mean()

np.float64(-4.736951571734001e-16)

In [6]:
transformed_data.std()

np.float64(1.0)

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
new_values=scaler.fit_transform(df['PetalLengthCm'].values.reshape(-1, 1))
new_values

array([[0.06779661],
       [0.06779661],
       [0.05084746],
       [0.08474576],
       [0.06779661],
       [0.11864407],
       [0.06779661],
       [0.08474576],
       [0.06779661],
       [0.08474576],
       [0.08474576],
       [0.10169492],
       [0.06779661],
       [0.01694915],
       [0.03389831],
       [0.08474576],
       [0.05084746],
       [0.06779661],
       [0.11864407],
       [0.08474576],
       [0.11864407],
       [0.08474576],
       [0.        ],
       [0.11864407],
       [0.15254237],
       [0.10169492],
       [0.10169492],
       [0.08474576],
       [0.06779661],
       [0.10169492],
       [0.10169492],
       [0.08474576],
       [0.08474576],
       [0.06779661],
       [0.08474576],
       [0.03389831],
       [0.05084746],
       [0.08474576],
       [0.05084746],
       [0.08474576],
       [0.05084746],
       [0.05084746],
       [0.05084746],
       [0.10169492],
       [0.15254237],
       [0.06779661],
       [0.10169492],
       [0.06779661],
       [0.08474576],
       [0.06779661],
       [0.62711864],
       [0.59322034],
       [0.66101695],
       [0.50847458],
       [0.61016949],
       [0.59322034],
       [0.62711864],
       [0.38983051],
       [0.61016949],
       [0.49152542],
       [0.42372881],
       [0.54237288],
       [0.50847458],
       [0.62711864],
       [0.44067797],
       [0.57627119],
       [0.59322034],
       [0.52542373],
       [0.59322034],
       [0.49152542],
       [0.6440678 ],
       [0.50847458],
       [0.66101695],
       [0.62711864],
       [0.55932203],
       [0.57627119],
       [0.6440678 ],
       [0.6779661 ],
       [0.59322034],
       [0.42372881],
       [0.47457627],
       [0.45762712],
       [0.49152542],
       [0.69491525],
       [0.59322034],
       [0.59322034],
       [0.62711864],
       [0.57627119],
       [0.52542373],
       [0.50847458],
       [0.57627119],
       [0.61016949],
       [0.50847458],
       [0.38983051],
       [0.54237288],
       [0.54237288],
       [0.54237288],
       [0.55932203],
       [0.33898305],
       [0.52542373],
       [0.84745763],
       [0.69491525],
       [0.83050847],
       [0.77966102],
       [0.81355932],
       [0.94915254],
       [0.59322034],
       [0.89830508],
       [0.81355932],
       [0.86440678],
       [0.69491525],
       [0.72881356],
       [0.76271186],
       [0.6779661 ],
       [0.69491525],
       [0.72881356],
       [0.76271186],
       [0.96610169],
       [1.        ],
       [0.6779661 ],
       [0.79661017],
       [0.66101695],
       [0.96610169],
       [0.66101695],
       [0.79661017],
       [0.84745763],
       [0.6440678 ],
       [0.66101695],
       [0.77966102],
       [0.81355932],
       [0.86440678],
       [0.91525424],
       [0.77966102],
       [0.69491525],
       [0.77966102],
       [0.86440678],
       [0.77966102],
       [0.76271186],
       [0.6440678 ],
       [0.74576271],
       [0.77966102],
       [0.69491525],
       [0.69491525],
       [0.83050847],
       [0.79661017],
       [0.71186441],
       [0.6779661 ],
       [0.71186441],
       [0.74576271],
       [0.69491525]])

In [ ]:
#maxabsscaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

mmscaler = MinMaxScaler(feature_range=(0,1))

df['MM_Scaled_SepalLengthCM'] = mmscaler.fit_transform(df[['PetalLengthCm']])

df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,MM_Scaled_SepalLengthCM
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.067797
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.067797
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.050847
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.084746
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.067797

In [10]:
from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()
maxab_values = scaler.fit_transform(df['PetalLengthCm'].values.reshape(-1,1) )
maxab_values

array([[0.20289855],
       [0.20289855],
       [0.1884058 ],
       [0.2173913 ],
       [0.20289855],
       [0.24637681],
       [0.20289855],
       [0.2173913 ],
       [0.20289855],
       [0.2173913 ],
       [0.2173913 ],
       [0.23188406],
       [0.20289855],
       [0.15942029],
       [0.17391304],
       [0.2173913 ],
       [0.1884058 ],
       [0.20289855],
       [0.24637681],
       [0.2173913 ],
       [0.24637681],
       [0.2173913 ],
       [0.14492754],
       [0.24637681],
       [0.27536232],
       [0.23188406],
       [0.23188406],
       [0.2173913 ],
       [0.20289855],
       [0.23188406],
       [0.23188406],
       [0.2173913 ],
       [0.2173913 ],
       [0.20289855],
       [0.2173913 ],
       [0.17391304],
       [0.1884058 ],
       [0.2173913 ],
       [0.1884058 ],
       [0.2173913 ],
       [0.1884058 ],
       [0.1884058 ],
       [0.1884058 ],
       [0.23188406],
       [0.27536232],
       [0.20289855],
       [0.23188406],
       [0.20289855],
       [0.2173913 ],
       [0.20289855],
       [0.68115942],
       [0.65217391],
       [0.71014493],
       [0.57971014],
       [0.66666667],
       [0.65217391],
       [0.68115942],
       [0.47826087],
       [0.66666667],
       [0.56521739],
       [0.50724638],
       [0.60869565],
       [0.57971014],
       [0.68115942],
       [0.52173913],
       [0.63768116],
       [0.65217391],
       [0.5942029 ],
       [0.65217391],
       [0.56521739],
       [0.69565217],
       [0.57971014],
       [0.71014493],
       [0.68115942],
       [0.62318841],
       [0.63768116],
       [0.69565217],
       [0.72463768],
       [0.65217391],
       [0.50724638],
       [0.55072464],
       [0.53623188],
       [0.56521739],
       [0.73913043],
       [0.65217391],
       [0.65217391],
       [0.68115942],
       [0.63768116],
       [0.5942029 ],
       [0.57971014],
       [0.63768116],
       [0.66666667],
       [0.57971014],
       [0.47826087],
       [0.60869565],
       [0.60869565],
       [0.60869565],
       [0.62318841],
       [0.43478261],
       [0.5942029 ],
       [0.86956522],
       [0.73913043],
       [0.85507246],
       [0.8115942 ],
       [0.84057971],
       [0.95652174],
       [0.65217391],
       [0.91304348],
       [0.84057971],
       [0.88405797],
       [0.73913043],
       [0.76811594],
       [0.79710145],
       [0.72463768],
       [0.73913043],
       [0.76811594],
       [0.79710145],
       [0.97101449],
       [1.        ],
       [0.72463768],
       [0.82608696],
       [0.71014493],
       [0.97101449],
       [0.71014493],
       [0.82608696],
       [0.86956522],
       [0.69565217],
       [0.71014493],
       [0.8115942 ],
       [0.84057971],
       [0.88405797],
       [0.92753623],
       [0.8115942 ],
       [0.73913043],
       [0.8115942 ],
       [0.88405797],
       [0.8115942 ],
       [0.79710145],
       [0.69565217],
       [0.7826087 ],
       [0.8115942 ],
       [0.73913043],
       [0.73913043],
       [0.85507246],
       [0.82608696],
       [0.75362319],
       [0.72463768],
       [0.75362319],
       [0.7826087 ],
       [0.73913043]])